export const importErrorCodes = [
  'SOURCE_UNAVAILABLE',
  'SOURCE_PRIVATE_OR_LOGIN_REQUIRED',
  'SOURCE_REMOVED',
  'SOURCE_UNSUPPORTED',
  'SOURCE_BLOCKED',
  'SOURCE_METADATA_ONLY',
  'PROVIDER_RATE_LIMITED',
  'MEDIA_TOO_LARGE_OR_LONG',
  'MEDIA_DOWNLOAD_DISABLED',
  'MEDIA_PROCESSING_FAILED',
  'RECIPE_NOT_FOUND',
  'INGREDIENTS_NOT_FOUND',
  'SCALABLE_AMOUNTS_NOT_FOUND',
  'SERVING_YIELD_MISSING',
  'EXTRACTION_SCHEMA_INVALID',
  'ANALYSIS_FAILED',
] as const;

export type ImportErrorCode = (typeof importErrorCodes)[number];
